### ISSUE TITLE
Filenames with hyphens "-"

### ISSUE THREAD

**Issue by djoks** [livewire/volt#91]
### Volt Version

1.6

### Laravel Version

10.10

### PHP Version

8.3.1

### Description

I do not know if this has already been mentioned however I struggled getting my volt component to work, my file name "location-picker" seemed to be the cause.   My methods were not recognized and neither were some other features I was expecting to work.  Also I was any to use props within my component.

I do not see any mention of this in the docs about filenames not supposed to have hyphens.

### Steps To Reproduce

Create a simple volt component with a hyphen in its name. eg. "example-picker.blade.php"
Create some state values and methods.
Try accessing them from the view.
Try displaying the value of any one of the components props.

**Comment by inmanturbo** [comment]
Have you gotten any other components working in your app, or is it just the one?

**Comment by djoks** [comment]
> Have you gotten any other components working in your app, or is it just the one?

So I created a new component with the exact same code but without a hyphen in the file name and it worked perfectly.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by nunomaduro** [comment]
Volt's internal test suite contains dozens of components with hyphens, and they are working as expected. Can you follow @driesvints's instructions to create a reproduceable scenario please?

 <img width="303" alt="Screenshot 2024-02-12 at 09 21 26" src="https://github.com/livewire/volt/assets/5457236/0237afa8-a259-4124-be10-03c69cc48104">

**Comment by nunomaduro** [comment]
Closing this issue due to the lack of activity.
