### ISSUE TITLE
Bug validate with Volt Functional API (duplicate errors, input message error without form.)

### ISSUE THREAD

**Issue by thaolaptrinh** [livewire/volt#93]
### Volt Version

1.0.0

### Laravel Version

10.10

### PHP Version

8.1

### Description

Bug validate with Volt Functional API (duplicate errors, render error input without form.)
![image](https://github.com/livewire/volt/assets/105599110/c9fac0f7-f8fa-4d39-ad33-9bf4a02d35ac)
![image](https://github.com/livewire/volt/assets/105599110/1d53bfe9-8c3c-43ba-a5d9-759db9b819e8)

### Steps To Reproduce

Initial project with breeze and install with Volt Functional API.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by nunomaduro** [comment]
I am unable to reproduce it:

<img width="446" alt="Screenshot 2024-03-25 at 17 24 46" src="https://github.com/livewire/volt/assets/5457236/5ef9a1d9-5d20-4d3e-9a0b-3ab3e210fdb7">

As @driesvints said, try to create a repository where we can reproduce the issue.

**Comment by dencarlsson** [comment]
@driesvints @nunomaduro I found a similar thing where I get duplicated/sticky error messages in a Volt component with a FormObject with validation.

I tried to install a fresh laravel/breeze install with both class and functional Volt components. Just by changing from `wire:model` to `wire:model.live` or `wire:model.blur` for the email input on the login page will reproduce it for me and a colleague.

It seems like theres some issues with the store updating correctly when using a FormObject.
The "The email field is required." message sticks around even if theres data in the input field and also the "The email field must be a valid email address." gets duplicated.

![duplicated-and-stickty-formobject-error-message](https://github.com/user-attachments/assets/fda6f194-f41c-4649-af52-295d552dc7aa)
